version: "3.3"
services:
  backend:
    build: ./backend
    ports:
      - 8000:8080
    restart: unless-stopped
    volumes:
      - upload:/upload
    environment:
      DATABASE_CONNECTION: mongodb://db/gant
  db:
    image: mongo:4.0-xenial
    ports:
      - 2747:27017
    restart: unless-stopped
    volumes:
      - association:/data/db
  web:
    build: ./frontend
    ports:
      - 3000:80
    restart: unless-stopped
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  association:
  upload:
